### ISSUE TITLE
Size of the "extended_attributes" field of the "rse_protocols" table

### ISSUE THREAD

**Issue by sartiran** [rucio/rucio#1543]
Motivation
----------
In order to use the CMS TFC lfn2pfn plugin we currently store, in json format, the TFC rules (a stack of regexp of the LFN to PFN translation) in the extended_attributes of the RSE protocol. Like in

```
Protocols:
==========
  srm
    extended_attributes: {u'space_token': u'CMS', u'tfc_proto': u'srmv2', u'web_service_path': u'/srm/managerv2?SFN=', u'tfc': [{u'protocol': u'direct', u'result': u'/dpm/in2p3.fr/home/cms/trivcat/store/PhEDEx_Debug/LoadTest07_GRIFLLR/LoadTest07_GRIFLLR_$1', u'element_name': u'lfn-to-pfn', u'path-match': u'/store/PhEDEx_Debug/LoadTest07Source/GRIF_LLR_(\\S+)'}, {u'protocol': u'direct', u'result': u'/dpm/in2p3.fr/home/cms/trivcat/store/PhEDEx_Debug/LoadTest07_GRIFLLR', u'element_name': u'lfn-to-pfn', u'path-match': u'/store/PhEDEx_Debug/LoadTest07Source'}, {u'protocol': u'direct', u'result': u'/dpm/in2p3.fr/home/cms/trivcat/store/PhEDEx_Debug/LoadTest07_GRIFLLR/LoadTest07_GRIFLLR_$1', u'element_name': u'lfn-to-pfn', u'path-match': u'.*/LoadTest07_GRIF_LLR_(.*)_.*_.*'}, {u'destination-match': u'.*', u'protocol': u'direct', u'result': u'/dpm/in2p3.fr/home/cms/trivcat/$1', u'element_name': u'lfn-to-pfn', u'path-match': u'/+(.*)'}, {u'protocol': u'srmv2', u'chain': u'direct', u'destination-match': u'.*', u'result': u'srm://polgrid4.in2p3.fr:8446/srm/managerv2?SFN=/$1', u'path-match': u'/+(.*)', u'element_name': u'lfn-to-pfn'}]}
    hostname: polgrid4.in2p3.fr
    prefix: /dpm/in2p3.fr/home/cms
    domains: {u'wan': {u'read': 1, u'write': 0, u'third_party_copy': 0, u'delete': 0}, u'lan': {u'read': 0, u'write': 0, u'delete': 0}}
    scheme: srm
    port: 8446
    impl: rucio.rse.protocols.gfalv2.Default
...
```

The size of the field is currently VARCHAR2(1024).
That's enough to contain all the relevant rules of the TFC tested so far (LLR and Nebraska) but bigger TFC may not fit into this.

Modification
------------
Talking with Mario Lassnig: it may be worth to migrate the extended_attribute field to an arbitrary size json encoded field (like for the DID metadata). This can be done over the timescale of a couple of releases.
That will provide us with a definitive solution for entering the TFC rules in the RSE metadata.
In the meanwhile most of the current TFC should fit in to the current size (I'll double-check this).
