### ISSUE TITLE
Belle II : Add Belle II tests

### ISSUE THREAD

**Issue by cserf** [rucio/rucio#4864]
Motivation
----------
In some recent release, there was a regression affecting RSE expression for RSE following the Belle II convention. In addition, there is no test for Dirac methods.

Modification
------------
Will introduce some Belle II specific tests to cover the issues mentioned above

**Comment by maany** [comment]
Hey @cserf , with the VO test framework introduced in #5286, you can start adding the Belle II tests.
Take a look at the build matrix for votests:
https://github.com/rucio/rucio/blob/af8b594b621077b270b03024a803d124385296c0/etc/docker/test/matrix_policy_package_tests.yml

You'll have to add a new section for belleii, like we have for Atlas. 
It would look something like:

```
belleii:
  installation_cmd: ""
  config_overrides:
    permission: belleii
    extract_scope:  belleii
    schema: belleii
    lfn2pfn_algorithm_default: "belleii"
  tests:
    allow:
      - rucio_tests
      - rucio_tests/belleii
    deny:
      - rucio_tests/belleii/test_belleii.py
  rdbms: 
    - postgres12
  python:
    - "3.6"
  dists:
    - centos7
  image_identifier: 
    - belleii
```

Lemme know if I can explain anything better ;)
