### ISSUE TITLE
Add_header lint job checks out wrong commit

### ISSUE THREAD

**Issue by joeldierkes** [rucio/rucio#5197]
Motivation
----------
The `GitHub Checkout Actions` checks out the wrong commit when the commit is force-pushed.
![add_header_job_screenshot](https://user-images.githubusercontent.com/8125678/151518825-f279bc11-153f-49ba-bfbb-571f2bd7c3a2.jpeg)
This is related to https://github.com/actions/checkout/issues/299.

Modification
------------
Check out the commit used for the pull-request.
```
- name: Checkout code
  uses: actions/checkout@v2
  with:
    # Check out pull request's HEAD commit instead of the merge commit to
    # work-around an issue where wrong a commit is being checked out.
    # For more details, see:
    # https://github.com/actions/checkout/issues/299.
    ref: ${{ github.event.pull_request.head.sha }}
```
