### ISSUE TITLE
Rucio support for S3 storages

### ISSUE THREAD

**Issue by rizart** [rucio/rucio#5284]
This is a general ticket in order to discuss Rucio support for S3 storages and gather troubleshooting information.

Please refer to this [1] draft documentation as a starting point.

[1] https://docs.google.com/document/d/1ofV5iIgpCKCnANNuqIavN_6FvvMTE6QPtQKK_n1P3SE

**Comment by alibeknow** [comment]
how can i run rucio with s3 storage can someone help me ?

**Comment by rizart** [comment]
Hello @alibeknow, please take a look at this [1] document as a starting point.

[1] https://docs.google.com/document/d/1ofV5iIgpCKCnANNuqIavN_6FvvMTE6QPtQKK_n1P3SE

**Comment by alibeknow** [comment]
@rizart  thanks a lot for your example! But i still has a problem with add rse s3 in rucio 
we are doing the project for **STFC DIRAC**
```
#CREATE RSE:
rucio-admin rse add AWSS3 
#CREATE PROTOCOL:
rucio-admin rse add-protocol \
--hostname s3.amazonaws.com \
--scheme  s3 \
--domain-json '{"wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 1}}' \
--prefix '/mynewbucketalibek' \
--port 80 \
--impl rucio.rse.protocols.s3boto.Default \
AWSS3

#CREATE ATTRIBUTES:
rucio-admin rse set-attribute --rse AWSS3 --key sign_url --value s3
rucio-admin rse set-attribute --rse AWSS3 --key skip_upload_stat --value True
rucio-admin rse set-attribute --rse AWSS3 --key verify_checksum --value false
rucio-admin rse set-attribute --rse AWSS3 --key strict_copy --value True

vim /opt/rucio/etc/rse-accounts.cfg
{
    "f4dc2967e329vdf5a73c154eb8d9ffae": { #rse_ID you can get it rucio-admin rse info AWSS3
        "access_key": "AWSS_ACCESSKEY",
        "secret_key": "AWS SECRET",
        "signature_version": "s3v4",
        "region": " eu-north-1"
    }
}
#CREATE USER ATTRIBUTE
rucio-admin account add-attribute root --key sign-gcs --value true
```

maybe i do something wrong ? What my next actions ?

**Comment by rizart** [comment]
Hello @alibeknow ,

I see that you have not really configured your RSE as the example in the document. A couple of points:
* The document describes a configuration where GFAL & FTS3 are used in order to access and transfer data. In this respect, I have not really tried the `s3boto` module.
* The steps described in the document might not be conclusive, several people have been trying to integrate resources based on that recipe, and sometimes things do not work as expected (this could be due to GFAL issues, or storage issues, or some dev work that could be needed on the Rucio side)

I would propose you start testing your configuration with simple uploads/downloads and then you can present here the errors that you get when trying these operations.

**Comment by alibeknow** [comment]
@rizart  Thanks a lot for your support!
  https
    domains: '{"lan": {"read": 1, "write": 1, "delete": 1}, "wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 1}}'
    extended_attributes: None
    hostname: <URL> **what i must put here url my bucket ?**
    impl: rucio.rse.protocols.gfal.Default
    port: 443
    prefix: <PATH>  **Here i must put path to my bucket ?**
    scheme: https

**Comment by rizart** [comment]
* `hostname: what i must put here url my bucket ?`
Here you should put your hostname. 
* `prefix: Here i must put path to my bucket?`
Yes.

Please note that Rucio currently signs URLs with the assumption that your bucket name is in the path ([Path-Style Requests](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html)) , e.g. `https://hostname/bucket-name/key-name` and not [Virtual Hosted-Style Requests](https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html), e.g. `https://bucket-name.hostname/key-name`.

**Comment by alibeknow** [comment]
@rizart  i'm updated my config like your in instruction basicly what i wan't to do i want after uploaded on any FTS then in cloud storage like AWS
so what i do 
1.I create cloud storage (AWS s3 interface compitable)
2.Create rule in replicate data
3.Trying trasnfer the data and recieve this error
```

CREATE RSE:
rucio-admin rse add AWSS3 
CREATE PROTOCOL:
rucio-admin rse add-protocol \
--hostname 127.0.0.1:7777 \
--scheme  http \
--domain-json '{"wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 1}}' \
--prefix 'bucket-name' \
--port 80 \
--impl rucio.rse.protocols.gfal.Default \
AWSS3

CREATE ATTRIBUTES:
rucio-admin rse set-attribute --rse AWSS3 --key sign_url --value s3
rucio-admin rse set-attribute --rse AWSS3 --key skip_upload_stat --value True
rucio-admin rse set-attribute --rse AWSS3 --key verify_checksum --value false
rucio-admin rse set-attribute --rse AWSS3 --key strict_copy --value True

vim /opt/rucio/etc/rse-accounts.cfg
{
    "8282eee9d2214e74be04f8cb8e2cd74f": { 
        "access_key": "ACCESSJEY",
        "secret_key": "SECRETKEY",
        "signature_version": "s3v4",
        "region": "eu1.storjshare.io"
    }
}
CREATE USER ATTRIBUTE
rucio-admin account add-attribute root --key sign-gcs --value true


```
and i recieve now error: 
```

Id:                         7f6e46d8401f46b59bc197bded1499ea
Account:                    root
Scope:                      test
Name:                       container
RSE Expression:             AWSS3
Copies:                     1
State:                      STUCK
Locks OK/REPLICATING/STUCK: 0/0/4
Grouping:                   DATASET
Expires at:                 None
Locked:                     False
Weight:                     None
Created at:                 2022-03-28 13:23:35
Updated at:                 2022-03-28 13:41:56
Error:                      RequestErrMsg.NO_SOURCES:RequestState.NO_SOURCES
Subscription Id:            None
Source replica expression:  None
Activity:                   User Subscriptions
Comment:                    None
Ignore Quota:               False
Ignore Availability:        False
Purge replicas:             False
Notification:               NO
End of life:                None
Child Rule Id:              None
```

RSE SETTINGS: 
```
Settings:
=========
  availability_delete: True
  availability_read: True
  availability_write: True
  credentials: None
  delete_protocol: 1
  deterministic: True
  domain: ['lan', 'wan']
  id: 8282eee9d2214e74be04f8cb8e2cd74f
  lfn2pfn_algorithm: hash
  qos_class: None
  read_protocol: 1
  rse: AWSS3
  rse_type: DISK
  sign_url: s3
  staging_area: False
  third_party_copy_protocol: 1
  third_party_copy_read_protocol: 1
  third_party_copy_write_protocol: 1
  verify_checksum: False
  volatile: False
  write_protocol: 1
Attributes:
===========
  AWSS3: True
  sign_url: s3
  skip_upload_stat: True
  strict_copy: True
  verify_checksum: False
Protocols:
==========
  http
    domains: '{"lan": {"read": 0, "write": 0, "delete": 0}, "wan": {"read": 1, "write": 1, "delete": 1, "third_party_copy": 1, "third_party_copy_read": 1, "third_party_copy_write": 1}}'
    extended_attributes: None
    hostname: 127.0.0.1:7777
    impl: rucio.rse.protocols.gfal.Default
    port: 80
    prefix: bucket-name
    scheme: http
Usage:
======
  rucio
    files: 0
    free: None
    rse: AWSS3
    rse_id: 8282eee9d2214e74be04f8cb8e2cd74f
    source: rucio
    total: 0
    updated_at: 2022-03-28 13:21:23
    used: 0
RSE limits:
===========
```
